### ISSUE TITLE
Unterschied zum developer-Addon?

### ISSUE THREAD

**Issue by alexplusde** [MisterRoot/redaxo_sync#1]
Hallo!

Mir ist laut der Beschreibung nicht ganz klar, wo hier der Unterschied zum developer-Addon liegt. 

VG
Alex

**Comment by crypto-scythe** [comment]
So wie es aussieht ist die Synchronisierung One-Way in Richtung Redaxo im Gegensatz zum Developer Addon welches ja in beide Richtungen geht. Ist nützlich sein wenn man die Templates/Module/Actions mit Git verwaltet, beim Developer Addon hatte ich schon ein paar Probleme dass er mir neue Module gelöscht hat :/

**Comment by MisterRoot** [comment]
Ich muss gestehen, ich habe nie das developer-Addon benutzt. 
Schon immer war der rex_sync bei mir im Einsatz und diesen habe ich für Redaxo 5 auch übernommen bzw. dieses Addon dafür gemacht.

Wie @crypto-scythe schon erwähnt hat, funktioniert dieses hier nur Richtung Redaxo
